WHITE_ON_BLACK = 1
BLACK_ON_WHITE = 2
YELLOW_ON_BLACK = 3
RED_ON_BLACK = 4
BLUE_ON_BLACK = 5
GREEN_ON_BLACK = 6
CYAN_ON_BLACK = 7
MAGENTA_ON_BLACK = 8
LIGHTS_COLORS = [WHITE_ON_BLACK, YELLOW_ON_BLACK, RED_ON_BLACK, BLUE_ON_BLACK, CYAN_ON_BLACK,
        MAGENTA_ON_BLACK]
